"""Build-time cffi builder for compiled out-of-line mode.

Defines all C API cdef declarations and provides a configure() function
that setup.py calls with build-time parameters (library_dirs, rpath, etc.)
before invoking ffibuilder.compile().
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from cffi import FFI


ffibuilder = FFI()

# Minimal C preamble for set_source — includes standard headers for the
# types used in the cdef (uint8_t, size_t, etc.). Opaque struct typedefs
# are generated by cffi from the cdef; no real WaveDB headers needed.
# raw_op_t and raw_result_t are fully declared here (not in cdef) so cffi
# uses this definition for field access without generating a conflicting one.
_C_SOURCE = """
#include <stdint.h>
#include <stddef.h>

/* Forward-declare ALL opaque types used in function signatures.
   cffi generates the actual typedefs later in the file, but the
   _cffi_d_ check functions at the top reference the type names
   before the definitions appear. Forward-declaring here avoids
   "unknown type name" errors. These must match the cdef exactly. */
typedef struct refcounter_s refcounter_t;
typedef struct database_s database_t;
typedef struct database_config_s database_config_t;
typedef struct encrypted_database_config_s encrypted_database_config_t;
typedef struct promise_s promise_t;
typedef struct async_error_s async_error_t;
typedef struct database_iterator_s database_iterator_t;
typedef struct path_s path_t;
typedef struct identifier_s identifier_t;
typedef struct database_subtree_s database_subtree_t;
typedef struct graph_layer_config_s graph_layer_config_t;
typedef struct graph_layer_s graph_layer_t;
typedef struct graph_query_s graph_query_t;
typedef struct graph_result_s graph_result_t;
typedef struct graphql_layer_config_s graphql_layer_config_t;
typedef struct graphql_layer_s graphql_layer_t;
typedef struct graphql_result_s graphql_result_t;

/* Fully-declared structs (fields accessible from Python).
   cffi uses this definition for field access via the `...` form in cdef. */
typedef struct { const char* key; size_t key_len; const uint8_t* value; size_t value_len; int type; } raw_op_t;
typedef struct { char* key; size_t key_len; uint8_t* value; size_t value_len; } raw_result_t;
"""

# ---- Types ----
# All WaveDB structs are declared opaque via forward declarations.
# Works identically in API mode — cffi emits the typedef into the generated
# C file; no real header required.
ffibuilder.cdef("""
typedef struct refcounter_s refcounter_t;
typedef struct database_s database_t;
typedef struct database_config_s database_config_t;
typedef struct encrypted_database_config_s encrypted_database_config_t;
typedef struct promise_s promise_t;
typedef struct async_error_s async_error_t;
typedef struct database_iterator_s database_iterator_t;
typedef struct path_s path_t;
typedef struct identifier_s identifier_t;
typedef struct database_subtree_s database_subtree_t;
typedef struct graph_layer_config_s graph_layer_config_t;
typedef struct graph_layer_s graph_layer_t;
typedef struct graph_query_s graph_query_t;
typedef struct graph_result_s graph_result_t;
typedef struct graphql_layer_config_s graphql_layer_config_t;
typedef struct graphql_layer_s graphql_layer_t;
typedef struct graphql_result_s graphql_result_t;

typedef struct { ...; } raw_op_t;
typedef struct { ...; } raw_result_t;
""")

ffibuilder.cdef("""
uint8_t* identifier_get_data_copy(const identifier_t* id, size_t* out_len);
void identifier_destroy(identifier_t* id);
void* refcounter_reference(void* refcounter);
""")

ffibuilder.cdef("""
/* unused in v1 — Python uses database_create_with_config */
database_t* database_create(const char* location, size_t lru_memory_mb,
    void* wal_config, uint8_t chunk_size, uint32_t btree_node_size,
    uint8_t enable_persist, void* pool, void* wheel, int* error_code);
database_t* database_create_with_config(const char* location,
    database_config_t* config, int* error_code);
database_t* database_create_encrypted(const char* location,
    encrypted_database_config_t* config, int* error_code);
void database_destroy(database_t* db);

database_config_t* database_config_default(void);
database_config_t* database_config_copy(const database_config_t* config);
void database_config_destroy(database_config_t* config);
void database_config_set_chunk_size(database_config_t*, uint8_t);
void database_config_set_btree_node_size(database_config_t*, uint32_t);
void database_config_set_enable_persist(database_config_t*, uint8_t);
void database_config_set_lru_memory_mb(database_config_t*, size_t);
void database_config_set_lru_shards(database_config_t*, uint16_t);
void database_config_set_wal_sync_mode(database_config_t*, uint8_t);
void database_config_set_wal_debounce_ms(database_config_t*, uint64_t);
void database_config_set_worker_threads(database_config_t*, uint8_t);
void database_config_set_sync_only(database_config_t*, uint8_t);

encrypted_database_config_t* encrypted_database_config_default(void);
void encrypted_database_config_destroy(encrypted_database_config_t*);
void encrypted_database_config_set_type(encrypted_database_config_t*, int);
void encrypted_database_config_set_symmetric_key(encrypted_database_config_t*, const uint8_t*, size_t);
void encrypted_database_config_set_asymmetric_private_key(encrypted_database_config_t*, const uint8_t*, size_t);
void encrypted_database_config_set_asymmetric_public_key(encrypted_database_config_t*, const uint8_t*, size_t);
""")

ffibuilder.cdef("""
int database_put_sync_raw(database_t* db,
    const char* key, size_t key_len, char delimiter,
    const uint8_t* value, size_t value_len);
int database_get_sync_raw(database_t* db,
    const char* key, size_t key_len, char delimiter,
    uint8_t** value_out, size_t* value_len_out);
int database_delete_sync_raw(database_t* db,
    const char* key, size_t key_len, char delimiter);
void database_raw_value_free(uint8_t* value);
int database_batch_sync_raw(database_t* db, char delimiter,
    const raw_op_t* ops, size_t count);
int database_scan_sync_raw(database_t* db,
    const char* prefix, size_t prefix_len, char delimiter,
    raw_result_t** results, size_t* count);
int database_scan_range_sync_raw(database_t* db,
    const char* start_prefix, size_t start_prefix_len,
    const char* end_prefix, size_t end_prefix_len,
    char delimiter,
    raw_result_t** results, size_t* count);
void database_raw_results_free(raw_result_t* results, size_t count);
""")

ffibuilder.cdef("""
int database_put_raw(database_t* db,
    const char* key, size_t key_len, char delimiter,
    const uint8_t* value, size_t value_len, promise_t* promise);
int database_get_raw(database_t* db,
    const char* key, size_t key_len, char delimiter, promise_t* promise);
int database_delete_raw(database_t* db,
    const char* key, size_t key_len, char delimiter, promise_t* promise);
int database_batch_raw(database_t* db, char delimiter,
    const raw_op_t* ops, size_t count, promise_t* promise);
""")

ffibuilder.cdef("""
typedef void (*promise_resolve_cb)(void* ctx, void* payload);
typedef void (*promise_reject_cb)(void* ctx, async_error_t* error);
promise_t* promise_create(promise_resolve_cb resolve, promise_reject_cb reject, void* ctx);
void promise_destroy(promise_t* promise);
void promise_resolve(promise_t* promise, void* payload);
void promise_reject(promise_t* promise, async_error_t* error);
const char* error_get_message(async_error_t* error);
const char* error_get_file(async_error_t* error);
const char* error_get_function(async_error_t* error);
int error_get_line(async_error_t* error);
void error_destroy(async_error_t* error);
""")

ffibuilder.cdef("""
/* unused in v1 — Task 10 iterator uses database_scan_range_sync_raw (string-based) */
database_iterator_t* database_scan_start(database_t* db,
    path_t* start_path, path_t* end_path);
int database_scan_next(database_iterator_t* iter,
    path_t** out_path, identifier_t** out_value);
void database_scan_end(database_iterator_t* iter);
""")

ffibuilder.cdef("""
database_subtree_t* database_subtree_open(database_t* db,
    const char* prefix, char delimiter);
int database_subtree_delete_prefix(database_t* db,
    const char* prefix, char delimiter);
void database_subtree_close(database_subtree_t* subtree);
int database_subtree_put_sync_raw(database_subtree_t* st,
    const char* key, size_t key_len, char delimiter,
    const uint8_t* value, size_t value_len);
int database_subtree_get_sync_raw(database_subtree_t* st,
    const char* key, size_t key_len, char delimiter,
    uint8_t** value_out, size_t* value_len_out);
int database_subtree_delete_sync_raw(database_subtree_t* st,
    const char* key, size_t key_len, char delimiter);
int database_subtree_put_raw(database_subtree_t* st,
    const char* key, size_t key_len, char delimiter,
    const uint8_t* value, size_t value_len, promise_t* promise);
int database_subtree_get_raw(database_subtree_t* st,
    const char* key, size_t key_len, char delimiter, promise_t* promise);
int database_subtree_delete_raw(database_subtree_t* st,
    const char* key, size_t key_len, char delimiter, promise_t* promise);
""")

ffibuilder.cdef("""
graph_layer_t* graph_layer_create(const char* path,
    graph_layer_config_t* config, database_subtree_t* subtree,
    int* error_code);
void graph_layer_destroy(graph_layer_t* layer);
int graph_insert_sync(graph_layer_t* layer, const char* s, const char* p, const char* o);
graph_query_t* graph_query_create(graph_layer_t* layer);
void graph_query_destroy(graph_query_t* q);
int graph_query_vertex(graph_query_t* q, const char* id);
int graph_query_out(graph_query_t* q, const char* predicate);
int graph_query_in(graph_query_t* q, const char* predicate);
int graph_query_has(graph_query_t* q, const char* predicate, const char* value);
int graph_query_intersect(graph_query_t* q, graph_query_t* left, graph_query_t* right);
int graph_query_union(graph_query_t* q, graph_query_t* left, graph_query_t* right);
int graph_query_limit(graph_query_t* q, size_t limit);
graph_result_t* graph_query_execute_sync(graph_query_t* q);
size_t graph_result_count(graph_result_t* r);
const char* const* graph_result_vertices(graph_result_t* r);
void graph_result_destroy(graph_result_t* r);
""")

ffibuilder.cdef("""
graphql_layer_t* graphql_layer_create(const char* path,
    const graphql_layer_config_t* config, database_subtree_t* subtree,
    int* error_code);
void graphql_layer_destroy(graphql_layer_t* layer);
int graphql_schema_parse(graphql_layer_t* layer, const char* sdl, char** error_out);
graphql_result_t* graphql_query_sync(graphql_layer_t* layer, const char* query);
void graphql_result_destroy(graphql_result_t* r);
const char* graphql_result_to_json(graphql_result_t* result);
void free(void* ptr);
""")


def configure(library_dir: str, include_dirs: list[str] | None = None) -> None:
    """Call set_source with build-time parameters.

    setup.py calls this after the CMake build produces libwavedb.so in
    library_dir. The rpath ensures the compiled extension finds the .so
    at runtime relative to the package directory.
    """
    if sys.platform == "darwin":
        rpath = "@loader_path/_lib"
    elif sys.platform == "win32":
        rpath = None  # Windows: no rpath; .dll is in the same dir
    else:
        rpath = "$ORIGIN/_lib"

    extra_link_args = []
    if rpath:
        extra_link_args.append(f"-Wl,-rpath,{rpath}")

    kwargs = dict(
        libraries=["wavedb"],
        library_dirs=[library_dir],
        extra_link_args=extra_link_args,
    )
    if include_dirs:
        kwargs["include_dirs"] = include_dirs

    ffibuilder.set_source(
        "wavedb._native_ext",
        _C_SOURCE,
        **kwargs,
    )