#!/usr/bin/env node
// Cross-platform build script for WaveDB Node.js bindings.
//
// On npm install: ensures c_src/ is populated, then runs node-gyp.
// On Windows: patches generated .vcxproj files to remove LLD-specific
// LTO options and ClangCL toolset that MSVC doesn't support.

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const isWin = process.platform === 'win32';
const scriptDir = __dirname;
const nodejsDir = path.join(scriptDir, '..');

function findNodeGyp() {
  // Try local node_modules first (monorepo or dev install)
  const localGyp = path.join(nodejsDir, 'node_modules', '.bin', 'node-gyp');
  if (fs.existsSync(localGyp + (isWin ? '.cmd' : ''))) {
    return `"${localGyp}"`;
  }
  // Fall back to npx
  return 'npx node-gyp';
}

function run(cmd) {
  execSync(cmd, { stdio: 'inherit' });
}

function ensureCSources() {
  const cSrcDir = path.join(nodejsDir, 'c_src');
  const copyScript = path.join(scriptDir, 'copy-sources.js');
  const marker = path.join(cSrcDir, 'src', 'HBTrie', 'hbtrie.h');

  if (fs.existsSync(copyScript)) {
    // In a repo checkout — always refresh c_src/ from the current src/.
    // Skipping this when c_src/ already exists left stale vendored C source
    // in place after C-level fixes, producing a Node addon built against
    // out-of-date C code. copy-sources.js walks up to find the WaveDB root;
    // if it can't (e.g. installing from an npm tarball that ships only c_src/
    // and not the parent source tree), it exits 1 and we fall back to the
    // bundled c_src/ rather than failing the install.
    try {
      console.log('Refreshing c_src/ from current src/...');
      run(`node "${copyScript}"`);
      return;
    } catch (e) {
      if (fs.existsSync(marker)) {
        console.log('copy-sources.js could not locate the source tree; using pre-populated c_src/.');
        return;
      }
      console.error('copy-sources.js failed and c_src/ is empty.');
      process.exit(1);
    }
  }

  if (fs.existsSync(marker)) {
    console.log('No copy-sources.js; using pre-populated c_src/.');
    return;
  }

  console.error('c_src/ is empty and copy-sources.js is missing.');
  console.error('If installing from npm, the c_src/ directory should be included in the package.');
  process.exit(1);
}

function findFiles(dir, ext) {
  const results = [];
  function walk(d) {
    if (!fs.existsSync(d)) return;
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile() && entry.name.endsWith(ext)) results.push(full);
    }
  }
  walk(dir);
  return results;
}

function findVcxprojFiles() {
  // Start with build/ directory (always present after node-gyp configure)
  const buildDir = path.join(nodejsDir, 'build');
  let files = findFiles(buildDir, '.vcxproj');

  // node-addon-api's nothing.vcxproj can land in different locations depending
  // on npm's hoisting. Search for node-addon-api directories that contain
  // .vcxproj files (generated by node-gyp configure) that we haven't found yet.
  const napiLocations = [
    // Hoisted to top-level node_modules (fresh npm install)
    path.join(nodejsDir, '..', 'node-addon-api'),
    // Scoped install (e.g. @vijayee/node-addon-api)
    path.join(nodejsDir, '..', '@vijayee', 'node-addon-api'),
    // Nested inside package's node_modules
    path.join(nodejsDir, 'node_modules', 'node-addon-api'),
    // Inside build/node_modules (monorepo layout)
    path.join(buildDir, 'node_modules', 'node-addon-api'),
  ];

  for (const loc of napiLocations) {
    const vcxproj = path.join(loc, 'nothing.vcxproj');
    if (fs.existsSync(vcxproj) && !files.includes(vcxproj)) {
      files.push(vcxproj);
    }
  }

  return files;
}

function patchVcxprojForMSVC() {
  const files = findVcxprojFiles();

  for (const file of files) {
    let content = fs.readFileSync(file, 'utf8');
    let modified = false;

    // Remove LLD-specific LTO options that MSVC link.exe doesn't understand
    if (content.includes('/opt:lldltojobs=')) {
      content = content.replace(/\/opt:lldltojobs=\d+\s*/g, '');
      modified = true;
    }
    if (content.includes('-flto=thin')) {
      content = content.replace(/-flto=thin\s*/g, '');
      modified = true;
    }

    // Replace ClangCL toolset with MSVC v143 if ClangCL is not available
    if (content.includes('<PlatformToolset>ClangCL</PlatformToolset>')) {
      content = content.replace(/<PlatformToolset>ClangCL<\/PlatformToolset>/g,
        '<PlatformToolset>v143</PlatformToolset>');
      modified = true;
    }

    if (modified) {
      fs.writeFileSync(file, content);
    }
  }
}

// ── OpenSSL detection ──

function hasOpenSSLHeaders(root) {
  return fs.existsSync(path.join(root, 'include', 'openssl', 'evp.h'));
}

function findOpenSSLWindows() {
  const candidates = [
    process.env.OPENSSL_ROOT,
    'C:\\OpenSSL-Win64',
    'C:\\Program Files\\OpenSSL-Win64',
    'C:\\Program Files (x86)\\OpenSSL-Win64',
    'C:\\ProgramData\\chocolatey\\lib\\openssl\\tools',
    'C:\\vcpkg\\installed\\x64-windows',
    'C:\\vcpkg\\installed\\x86-windows',
    'C:\\msys64\\ucrt64',
    'C:\\msys64\\mingw64',
    'C:\\msys64\\mingw32',
  ].filter(Boolean);

  for (const root of candidates) {
    if (hasOpenSSLHeaders(root)) {
      return root;
    }
    // Some installers nest under an extra 'OpenSSL' folder
    const nested = path.join(root, 'OpenSSL');
    if (hasOpenSSLHeaders(nested)) {
      return nested;
    }
  }

  // Try to read a few common registry keys
  const regKeys = [
    'HKLM\\SOFTWARE\\OpenSSL',
    'HKLM\\SOFTWARE\\WOW6432Node\\OpenSSL',
    'HKLM\\SOFTWARE\\ShiningLight\\OpenSSL',
    'HKLM\\SOFTWARE\\WOW6432Node\\ShiningLight\\OpenSSL',
  ];
  for (const key of regKeys) {
    try {
      const out = execSync(`reg query "${key}" /s`, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] });
      const m = out.match(/InstallDir\s+REG_SZ\s+(.+)/m) || out.match(/(\w:\\[^\n]+OpenSSL[^\n]*)/mi);
      if (m) {
        const dir = m[1].trim();
        if (hasOpenSSLHeaders(dir)) return dir;
      }
    } catch (e) {
      // ignore
    }
  }

  return null;
}

function findOpenSSLUnix() {
  if (process.env.OPENSSL_ROOT) return process.env.OPENSSL_ROOT;

  const candidates = [
    '/usr',
    '/usr/local',
    '/opt/homebrew/opt/openssl',
    '/opt/homebrew/opt/openssl@3',
    '/opt/homebrew/opt/openssl@1.1',
  ];

  for (const root of candidates) {
    if (hasOpenSSLHeaders(root)) return root;
  }

  try {
    const out = execSync('pkg-config --variable=prefix openssl', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] }).trim();
    if (out && hasOpenSSLHeaders(out)) return out;
  } catch (e) {
    // ignore
  }

  return null;
}

function configureOpenSSL() {
  if (process.env.WAVEDB_OPENSSL === '0' || process.env.WAVEDB_NO_OPENSSL === '1') {
    console.log('OpenSSL explicitly disabled via WAVEDB_OPENSSL=0 / WAVEDB_NO_OPENSSL=1.');
    return;
  }

  const root = isWin ? findOpenSSLWindows() : findOpenSSLUnix();
  if (root) {
    console.log(`Detected OpenSSL at: ${root}`);
    process.env.WAVEDB_OPENSSL = '1';
    process.env.OPENSSL_ROOT = root;
    return;
  }

  if (isWin) {
    console.log('OpenSSL not detected on Windows; building without OpenSSL (WAVEDB_NO_OPENSSL).');
    process.env.WAVEDB_NO_OPENSSL = '1';
  } else {
    console.log('OpenSSL not detected; attempting system default link flags (-lcrypto -lssl).');
    // On Unix we still try to link against system OpenSSL even if headers weren't
    // found in the candidate prefixes. If that fails, the user can set WAVEDB_OPENSSL=0.
  }
}

// ── Main build flow ──

ensureCSources();
configureOpenSSL();

const nodeGyp = findNodeGyp();

if (isWin) {
  // On Windows: configure, patch vcxproj for MSVC, then build
  run(`${nodeGyp} configure`);
  patchVcxprojForMSVC();
  run(`${nodeGyp} build`);
} else {
  run(`${nodeGyp} rebuild`);
}